language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION='2.3.* symfony/expression-language:2.4.*'
    - php: 5.6
      env: SYMFONY_VERSION=2.4.*
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION='2.7.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.3.* symfony/expression-language:2.4.* m4tthumphrey/php-gitlab-api:6.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.4.* m4tthumphrey/php-gitlab-api:6.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.6.* m4tthumphrey/php-gitlab-api:6.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.7.* m4tthumphrey/php-gitlab-api:6.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.8.* m4tthumphrey/php-gitlab-api:6.*'
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - composer update --prefer-source

script: phpunit
